version: '3.8'
services:
  dev-db:
    image: postgres:14
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: explorer000
      POSTGRES_DB: sportskitermin
    networks:
      - freecodecamp
  test-db:
    image: postgres:14
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: explorer000
      POSTGRES_DB: sportskitermin
    networks:
      - freecodecamp
networks:
  freecodecamp:
